### ISSUE TITLE
What should the next version be? 

### ISSUE THREAD

**Issue by joesantos418** [arquivei/php-kafka-consumer#23]
Now that we are close to the next release, it becomes clear that the next step requires some discussion: what should the next version be?

There are two options: a minor (2.3.0) and a major (3.0.0) and both can be defended.

There's no breaking of contract and no compatibility issues with the previous release. All work that has been done in the last months was towards tests and guaranteeing compatibility with dependencies. As a matter of fact very little, if anything at all, changed in the src folder. That is the case for a minor release.

On the other hand, we now have minimum requirements expressed explicitly, something we didn't have before and some legacy projects may still use unsupported versions of these requirements (like Laravel 5, for example). While updating the library itself shouldn't break any deployed applications, updating from Laravel 5 to 6 may do just that. In a sense we are indirectly breaking compatibility and therefore should create a major release.

I am inclined to take the major release route and if this discussion doesn't advance until november 20 by EOD GMT-3, that's the course I'll take.

EDIT: Changed the version to mean minor (2.3.0) instead of patch (2.2.1)

**Comment by diniz-victor** [comment]
Sounds good to me for us to follow the major release approach. That's my vote.

**Comment by andrelugomes** [comment]
I believe if has no breaking changes and no new features, a patch must be done or no release at all.

**Comment by joesantos418** [comment]
> I believe if has no breaking changes and no new features, a patch must be done or no release at all.

We can't not release at all, we have changes in the composer.json file. I am inclined towards a major release because the requirements are expressed in a more strict manner and may force users to update other dependencies in their applications.

**Comment by andrelugomes** [comment]
> > I believe if has no breaking changes and no new features, a patch must be done or no release at all.
> 
> We can't not release at all, we have changes in the composer.json file. I am inclined towards a major release because the requirements are expressed in a more strict manner and may force users to update other dependencies in their applications.

HUmm..

```
"require": {
    "php": "~7.2 || ~7.3 || ~7.4",
    "monolog/monolog": "~1 || ~2",
    "illuminate/console": "~6 || ~7 || ~8",
    "ext-rdkafka": "~3.0 || ~3.1 || ~4.0"
  },
```

Makes sense.

A major could be the best approach...

Voting for a major one :+1:

**Comment by fcoedno** [comment]
If there are no BC breaks I don't think it makes sense to create a major release. The clients of this lib will naturally have requirenments enforcement for the other dependencies, so no update would be made that could break their system.

Besides, I have the feeling that increasing the major version without BC break will limit us in actually introducing such BC breaks for future API improvements. In this sense, I believe that a minor version would suffice and only increment a major version when we see the need and opportunity to introduce BC breaks.

**Comment by joesantos418** [comment]
> The clients of this lib will naturally have requirenments enforcement for the other dependencies

I don't quite understand what you mean here, can you clarify?


> Besides, I have the feeling that increasing the major version without BC breaks would limit us in actually introducing such BC breaks for future API improvements.

What makes you feel that way? Why would the rationale for a major release now affect the rationale for future major releases?

**Comment by fcoedno** [comment]
@joesantos418 About the first point:

Just to start, I believe this should be a minor update and not a patch (from 2.2.0 -> 2.3.0). Then, If a client uses Laravel 5 which we don't explicitly support anymore tries to update his dependencies, composer won't update this lib to version 2.3 because the client's version constraints already enforces that laravel 5 must be used. And if this very same client wants to stil use our next release, he'll have to update laravel manually anyway, so this reasoning does not seem a valid argument towards upgrading a major version.

About the second point:

The point is that we would create a major release 3.0 without BC breaks, and the development of this 3.0 version we would be limited to only no-BC breaks changes. So, to actually introduce BC breaks we will have to move to a version 4.0. Personally as a client, when I see a new major version I will naturally try to avoid it at first, because of the friction of updating.

Also, by increasing the major version the client will have to manually update, so he cannot depend upon composer's ability to choose the latest possible version with a simple composer update. From the [docs](https://getcomposer.org/doc/articles/versions.md#caret-version-range-), the caret operator is the safest option for defining library dependencies following semver, like so:

```json
"require": {
  "arquivei/php-kafka-consumer": "^2.0"
}
```

When the client runs `composer update` composer will match the client's constraints with the package's constraints and then choose the latest possible version. If we just increment the minor version (from 2.2 -> 2.3) composer will automatically update it if the client also has the other constraints matching our requirements (for example, using laravel 6).

However, if we do a major increment, composer won't bring the 3.0 version due to semantic versioning. So why would we add this friction to update the lib if we didn't introduce any BC break?

Sure, if the client really likes our lib and keeps up-to-date with all the new releases, he will manually force an update to the 3.0 version but, again, this seems to me like an unecessary step.

At least this is my understanding about how composer would resolve the dependencies, but haven't found documentation to back this up. I'll do some testing here and then report my findings.

**Comment by joesantos418** [comment]
> minor update and not a patch (from 2.2.0 -> 2.3.0)

Thanks for noticing that, I updated the initial comment.

You are correct about how composer handles the changes but that's besides the point. The argument for a major release is that considering that the user wants to update to the newest version (whether composer notation will do it automatically or not) there may be indirect BC issues. Using a major version change will do a batter job at *communicating* that than a minor.

> The point is that we would create a major release 3.0 without BC breaks, and the development of this 3.0 version would be limited to only non-BC breaks changes.

You are absolutely right here. However, it has been the point of this new release to put this project in better shape (by adding tests, making sure we support everything we should, and so on) so we can *then* improve its core logic. If that requires two major releases in a row, that's the price we pay for letting it gather dust for so long. The best we can do for users is to be transparent about the complexity of updating.

**Comment by fcoedno** [comment]
As to my understanding, BC breaks are related to API changes not to dependencies update. We could completely remove a dependency, or add new ones, as long as the public facing API remains the same that would not define a BC break. And if there no BC breaks, there isn't a need for a major upgrade.

**Comment by joesantos418** [comment]
You are absolutely correct. I was concerned about communicating the possibility of user needing to update other dependencies they may have. Considering what the folks at https://semver.org/ have defined, I think the best route might actually be a patch with a warning in the release notes.

**Comment by joesantos418** [comment]
Version 2.2.1 has been released.
